### ISSUE TITLE
when i run app it shows me some error related to pubspec.yaml

### ISSUE THREAD

**Issue by gourav6m17** [david-legend/flutter_catalog#2]
"flutter generate" is deprecated, use "dart pub run build_runner" instead. 
The following dependencies must be added to dev_dependencies in pubspec.yaml:
build_runner: 1.10.0
functional_widget: ^0.7.2
generating build script...
Running "flutter pub get" in flutter_tool...
Exception: Error generating build_script snapshot: Could not find a file named "pubspec.yaml" in "/home/gourav/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-7.0.0".

Pubspec.yaml file

`name: fluttercatalog
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^1.1.0
  auto_route: ^0.6.1
  functional_widget_annotation: ^0.5.1
  flutter_feather_icons: ^1.0.3
  bubble_tab_indicator: "^0.1.4"
  font_awesome_flutter: ^8.8.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.0
  functional_widget: ^0.7.2
  auto_route_generator: ^0.6.0

builders:
  functional_widget: ^0.7.2
`

**Comment by david-legend** [comment]
Have you been able to fix it ??
Pull again and see if the problem still persists.

**Comment by basha97** [comment]
same issue for me ??
How to solve it

**Comment by gourav6m17** [comment]
> Have you been able to fix it ??
> Pull again and see if the problem still persists.

No, the issue is not fixed even i tried other alot

**Comment by gourav6m17** [comment]
Hey dear @david-legend I need your help brother

**Comment by david-legend** [comment]
Hi, I will get it fixed today, been busy that's why there has been response from me

**Comment by gourav6m17** [comment]
OK 
I'll be waiting for update.

**Comment by david-legend** [comment]
Please do check again and give me feedback. I have fixed it on my end and push new changes.
