### ISSUE TITLE
Does not compile on newest Flutter versions

### ISSUE THREAD

**Issue by JCKodel** [david-legend/flutter_catalog#3]
On https://github.com/david-legend/flutter_catalog/blob/3c400e8311542129a3ed404836c186de985e7377/lib/main.dart#L2, you need to add `hide Router` because new Flutter SDK contains a class named Router, which conflicts with other imports on this file.

```dart
import 'package:flutter/material.dart' hide Router;
```

**Comment by yusoofsh** [comment]
I would love to open PR's for this.

**Comment by david-legend** [comment]
Please do, I would love that

**Comment by fouyos** [comment]
If this also relevance for the title, can I open PR's on this? or i should create new issues?
![image](https://user-images.githubusercontent.com/18055365/96263421-2bb6d400-0fed-11eb-9e0a-ef2ad031ea6b.png)
